BEGIN;

-- BỔ SUNG CỘT IS_DISABLED VÀO BẢNG PUBLIC.PROFILES NẾU CHƯA TỒN TẠI
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_disabled BOOLEAN DEFAULT FALSE;

-- LÀM MỚI SCHEMA CACHE TRÊN SUPABASE
NOTIFY pgrst, 'reload schema';

COMMIT;
